const $=(id)=>document.getElementById(id),TOKEN_KEY='courier-radar-token',SHIFT_KEY='courier-radar-shift';let offers=[],currentPosition=null,heartbeatTimer=null;
const ZONES=[{name:'Downtown Culver',lat:34.0211,lng:-118.3965},{name:'Palms / Venice',lat:34.0228,lng:-118.42},{name:'Fox Hills',lat:33.9895,lng:-118.391},{name:'Koreatown',lat:34.0638,lng:-118.3008},{name:'USC',lat:34.0224,lng:-118.2851},{name:'DTLA',lat:34.0467,lng:-118.25}];
function token(){return localStorage.getItem(TOKEN_KEY)||''}function shift(){try{return JSON.parse(localStorage.getItem(SHIFT_KEY)||'null')}catch{return null}}function saveShift(v){v?localStorage.setItem(SHIFT_KEY,JSON.stringify(v)):localStorage.removeItem(SHIFT_KEY)}function headers(){return{'Content-Type':'application/json','x-capture-token':token()}}function money(n){return n==null?'—':`$${Number(n).toFixed(2)}`}function minsSince(iso){return Math.max(0,(Date.now()-new Date(iso).getTime())/60000)}
function blockFor(d=new Date()){const h=d.getHours()+d.getMinutes()/60;if(h>=6&&h<10.5)return'BREAKFAST';if(h>=10.5&&h<14.5)return'LUNCH';if(h>=14.5&&h<16.5)return'AFTERNOON';if(h>=16.5&&h<21)return'DINNER';if(h>=21||h<1)return'LATE';return'OFF-PEAK'}
function hav(a,b,c,d){const r=3958.8,p1=a*Math.PI/180,p2=c*Math.PI/180,dp=(c-a)*Math.PI/180,dl=(d-b)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*r*Math.asin(Math.sqrt(x))}
function zoneFor(lat,lng){if(!Number.isFinite(lat)||!Number.isFinite(lng))return'Unknown';let best={name:'Learning zone',d:Infinity};for(const z of ZONES){const d=hav(lat,lng,z.lat,z.lng);if(d<best.d)best={name:z.name,d}}return best.d<=2.2?best.name:'Learning zone'}
async function api(path,options={}){if(!token())throw new Error('Set your capture token first.');const r=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function getLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location unavailable'));navigator.geolocation.getCurrentPosition(p=>{currentPosition={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};resolve(currentPosition)},reject,{enableHighAccuracy:true,maximumAge:60000,timeout:8000})})}
async function pingPresence(event='heartbeat'){if(!shift()||!token())return;try{const p=await getLocation();await api('/api/presence',{method:'POST',body:JSON.stringify({...p,event})});render()}catch{}}
function offerBlock(o){return blockFor(new Date(o.captured_at))}
function offerEffectiveDph(o){if(!(Number(o.payout)>0))return null;const eta=Number(o.eta_minutes)||((Number(o.miles)||0)/11.5*60+5),shop=o.is_shop?Math.max(8,Math.min(25,(Number(o.item_count)||6)*1.2)):0,eff=Math.max(1,eta+shop+5);return Number(o.payout)/eff*60}
function historicalZones(){const block=blockFor(),relevant=offers.filter(o=>offerBlock(o)===block),groups={};for(const o of relevant){const z=o.zone||'Unknown';groups[z]??={zone:z,n:0,takes:0,dph:[]};groups[z].n++;if(['accepted','completed'].includes(o.state))groups[z].takes++;const d=offerEffectiveDph(o);if(d)groups[z].dph.push(d)}return Object.values(groups).map(g=>{const avg=g.dph.length?g.dph.reduce((a,b)=>a+b,0)/g.dph.length:0,confidence=Math.min(1,g.n/12),score=(avg||18)*(.55+.45*confidence)+Math.min(g.n,10)*.6;return{...g,avgDph:avg,confidence,score}}).sort((a,b)=>b.score-a.score)}
function recentOffers(minutes=60){const cutoff=Date.now()-minutes*60000;return offers.filter(o=>new Date(o.captured_at).getTime()>=cutoff)}function median(arr){if(!arr.length)return null;const a=[...arr].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function recommendation(){const s=shift();if(!s)return{advice:'START A SHIFT',reason:'Radar learns from captured offers and your location during each block.',radius:'2.5 mi',confidence:'LEARNING'};const last=offers[0],idle=last?minsSince(last.captured_at):minsSince(s.startedAt),currentZone=currentPosition?zoneFor(currentPosition.lat,currentPosition.lng):(last?.zone||'Unknown'),zones=historicalZones(),best=zones[0],here=zones.find(z=>z.zone===currentZone),sparse=(here?.n||0)<4;if(idle<8)return{advice:'STAY',reason:`Fresh ping ${Math.round(idle)}m ago. Keep the tight e-bike radius while flow is alive.`,radius:'2.5 mi',confidence:sparse?'LEARNING':'HIGH'};if(idle<15)return{advice:'WIDEN',reason:`${Math.round(idle)} idle minutes. Allow a slightly longer order only if payout clears your time floor.`,radius:'3.5 mi',confidence:sparse?'LEARNING':'MED'};if(best&&best.zone!==currentZone&&best.n>=3)return{advice:`MOVE → ${best.zone.toUpperCase()}`,reason:`${Math.round(idle)} idle minutes here. ${best.zone} has the strongest learned ${blockFor().toLowerCase()} offer profile (${best.n} observations).`,radius:'4–5 mi escape',confidence:best.confidence>.6?'HIGH':'MED'};return{advice:'ESCAPE MODE',reason:`${Math.round(idle)} idle minutes. Take a longer order only if it moves you toward a dense merchant area; otherwise relocate once and re-test.`,radius:'4–5 mi escape',confidence:'LEARNING'}}
function escapeHtml(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(){const s=shift();$('blockBadge').textContent=s?blockFor():'OFF';$('blockBadge').classList.toggle('live',!!s);const rec=recommendation();$('mainAdvice').textContent=rec.advice;$('adviceReason').textContent=rec.reason;$('radius').textContent=rec.radius;$('confidence').textContent=rec.confidence;const last=offers[0],idle=s?(last?minsSince(last.captured_at):minsSince(s.startedAt)):null;$('idle').textContent=idle==null?'—':`${Math.round(idle)}m`;$('zone').textContent=currentPosition?zoneFor(currentPosition.lat,currentPosition.lng):(last?.zone||'—');const rb=recentOffers(60).filter(o=>offerBlock(o)===blockFor());$('pingsHr').textContent=rb.length?rb.length.toFixed(1):'—';const md=median(rb.map(offerEffectiveDph).filter(Boolean));$('offerDph').textContent=md?`$${Math.round(md)}`:'—';const decisions=offers.filter(o=>['accepted','completed','rejected'].includes(o.state)),taken=decisions.filter(o=>['accepted','completed'].includes(o.state)).length;$('takeRate').textContent=decisions.length?`${Math.round(taken/decisions.length*100)}%`:'—';if(last){$('lastMerchant').textContent=last.merchant||'Unknown merchant';$('lastPay').textContent=money(last.payout);$('lastMiles').textContent=last.miles?`${Number(last.miles).toFixed(1)} mi`:'—';$('lastEta').textContent=last.eta_minutes?`${last.eta_minutes}m`:'—';const d=offerEffectiveDph(last),v=d>=35?'TAKE':d>=28.7?'BORDERLINE':'SKIP';$('lastVerdict').textContent=v+(d?` · $${Math.round(d)}/h`:'');$('lastVerdict').className=`pill ${v.toLowerCase()}`}const zones=historicalZones(),zl=$('zoneList');zl.innerHTML=zones.length?zones.slice(0,5).map((z,i)=>`<div class="zone-row"><div><div class="zone-name">${i===0?'◉ ':''}${escapeHtml(z.zone)}</div><div class="zone-meta">${z.n} offers · ${z.takes} taken · ${Math.round(z.confidence*100)}% confidence</div></div><div class="zone-score">${z.avgDph?`$${Math.round(z.avgDph)}/h`:'—'}</div></div>`).join(''):'<div class="empty">No observations for this time block yet. Capture offers; Radar will learn automatically.</div>';$('shiftBtn').textContent=s?'End shift':'Start shift'}
async function refresh(){if(!token())return render();try{const d=await api('/api/feed?hours=168');offers=d.offers||[]}catch(e){console.warn(e)}render()}
async function mark(state){try{await api('/api/action',{method:'POST',body:JSON.stringify({state})});await refresh()}catch(e){alert(e.message)}}
async function captureTest(){try{const p=await getLocation().catch(()=>({})),last=offers[0],idleMinutes=last?minsSince(last.captured_at):0,out=await api('/api/capture',{method:'POST',body:JSON.stringify({text:$('testText').value,...p,idleMinutes})});alert(`${out.verdict} · ${out.parsed.merchant||'merchant?'} · ${out.rate?`$${Math.round(out.rate.dollarsPerHour)}/hr`:'rate?'}`);await refresh()}catch(e){alert(e.message)}}
function updateClock(){const s=shift();if(!s){$('shiftClock').textContent='0:00';return}const sec=Math.floor((Date.now()-new Date(s.startedAt))/1000),h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60);$('shiftClock').textContent=`${h}:${String(m).padStart(2,'0')}`;render()}
async function toggleShift(){if(shift()){await pingPresence('shift_end');saveShift(null);clearInterval(heartbeatTimer);heartbeatTimer=null;render();return}saveShift({startedAt:new Date().toISOString()});await pingPresence('shift_start');startHeartbeat();render()}
function startHeartbeat(){if(heartbeatTimer)clearInterval(heartbeatTimer);if(shift())heartbeatTimer=setInterval(()=>pingPresence('heartbeat'),120000)}
$('token').value=token();$('saveToken').onclick=()=>{localStorage.setItem(TOKEN_KEY,$('token').value.trim());refresh()};$('refreshBtn').onclick=async()=>{await getLocation().catch(()=>null);await refresh()};$('acceptLast').onclick=()=>mark('accepted');$('rejectLast').onclick=()=>mark('rejected');$('testCapture').onclick=captureTest;$('shiftBtn').onclick=toggleShift;if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){pingPresence('visible');refresh()}});setInterval(updateClock,30000);setInterval(refresh,60000);startHeartbeat();getLocation().catch(()=>null).finally(refresh);updateClock();render();